### PR TITLE
Update to use Django 1.10 _meta API

### PR DESCRIPTION
**Pull request by scottp-dpaw**

### CODE REVIEW

**Comment by bruth** [comment]
@scottp-dpaw Thanks for the contribution! Do you mind updating the `.travis.yml` to reflect the supported versions?

**Comment by scottp-dpaw** [comment]
No worries. I wasn't sure if removing the older versions was the right approach, it wouldn't be the hardest thing in the world to check and stub in the old methods, I just ran out of time

**Comment by bruth** [comment]
@scottp-dpaw Thanks. Yes good point. I may just do that.

**Comment by bruth** [comment]
Or create and release a new major version with this change.

**Pull request merged**
